-- Taskly example schema + seed data (SQL Server port of seed.pg.sql — same tables, same rows).
-- Relationships are real foreign keys here — Graphoria introspects them into the
-- API graph automatically. The exception is task_tags, which carries no FKs; its
-- relationships (from tasks, and to tags) stay declared in graphoria.ts to
-- demonstrate the config-declared relationships feature.
--
-- Dialect notes vs the PostgreSQL file:
--   * Single batch, no GO separators — runnable in one pool.request().batch(seed).
--     CREATE OR ALTER must start its own batch, so the routines sit inside EXEC(N'...').
--   * IDENTITY replaces GENERATED BY DEFAULT AS IDENTITY; explicit seed ids need
--     SET IDENTITY_INSERT, and SQL Server reseeds past the max inserted id on its
--     own, so there is no setval() block.
--   * datetimeoffset replaces timestamptz.
--   * [plan] is bracket-quoted: PLAN is a reserved T-SQL keyword.
--   * task_age_days is a scalar UDF — T-SQL requires schema-qualified calls, so
--     the config must reference it as
--     virtualColumnFunction("age_days", "int", false, "dbo.task_age_days", ["created_at"]).
--   * project_stats is a PROCEDURE (not a table-returning function): Graphoria's
--     MSSQL engine introspects sys.procedures and invokes with EXEC.

IF OBJECT_ID(N'dbo.organizations', N'U') IS NULL
CREATE TABLE dbo.organizations (
  id         int IDENTITY(1,1) PRIMARY KEY,
  name       nvarchar(255) NOT NULL,
  slug       nvarchar(255) NOT NULL,
  [plan]     nvarchar(32)  NOT NULL DEFAULT 'free',  -- free | pro | enterprise
  created_at datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

IF OBJECT_ID(N'dbo.projects', N'U') IS NULL
CREATE TABLE dbo.projects (
  id          int IDENTITY(1,1) PRIMARY KEY,
  org_id      int NOT NULL CONSTRAINT projects_org_id_fkey REFERENCES dbo.organizations (id),
  owner       nvarchar(255) NOT NULL,                -- auth.user.username
  name        nvarchar(255) NOT NULL,
  description nvarchar(max),
  visibility  nvarchar(16) NOT NULL DEFAULT 'org',   -- private | org | public
  status      nvarchar(32) NOT NULL DEFAULT 'active',
  created_at  datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

IF OBJECT_ID(N'dbo.tasks', N'U') IS NULL
CREATE TABLE dbo.tasks (
  id          int IDENTITY(1,1) PRIMARY KEY,
  org_id      int NOT NULL CONSTRAINT tasks_org_id_fkey REFERENCES dbo.organizations (id),  -- denormalized → one-liner RBAC row filters
  project_id  int NOT NULL CONSTRAINT tasks_project_id_fkey REFERENCES dbo.projects (id),
  assignee    nvarchar(255),                         -- auth.user.username
  created_by  nvarchar(255) NOT NULL,
  title       nvarchar(255) NOT NULL,
  description nvarchar(max),
  status      nvarchar(32) NOT NULL DEFAULT 'todo',  -- todo | in_progress | done
  priority    int NOT NULL DEFAULT 3,                -- 1..5
  due_date    datetimeoffset,
  created_at  datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET(),
  updated_at  datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

IF OBJECT_ID(N'dbo.comments', N'U') IS NULL
CREATE TABLE dbo.comments (
  id         int IDENTITY(1,1) PRIMARY KEY,
  org_id     int NOT NULL CONSTRAINT comments_org_id_fkey REFERENCES dbo.organizations (id),
  task_id    int NOT NULL CONSTRAINT comments_task_id_fkey REFERENCES dbo.tasks (id),
  author     nvarchar(255) NOT NULL,
  body       nvarchar(max) NOT NULL,
  created_at datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

IF OBJECT_ID(N'dbo.tags', N'U') IS NULL
CREATE TABLE dbo.tags (
  id     int IDENTITY(1,1) PRIMARY KEY,
  org_id int NOT NULL CONSTRAINT tags_org_id_fkey REFERENCES dbo.organizations (id),
  name   nvarchar(255) NOT NULL,
  color  nvarchar(16)  NOT NULL DEFAULT '#888888'
);

-- Intentionally FK-free: task_tags' relationships (from tasks, to tags) are
-- declared in graphoria.ts to demonstrate config-declared relationships.
IF OBJECT_ID(N'dbo.task_tags', N'U') IS NULL
CREATE TABLE dbo.task_tags (
  task_id int NOT NULL,
  tag_id  int NOT NULL,
  PRIMARY KEY (task_id, tag_id)
);

IF OBJECT_ID(N'dbo.audit_log', N'U') IS NULL
CREATE TABLE dbo.audit_log (
  id         int IDENTITY(1,1) PRIMARY KEY,
  org_id     int NOT NULL CONSTRAINT audit_log_org_id_fkey REFERENCES dbo.organizations (id),
  actor      nvarchar(255) NOT NULL,
  action     nvarchar(255) NOT NULL,
  entity     nvarchar(255) NOT NULL,
  created_at datetimeoffset NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

-- Function backing the `age_days` virtual column (call it as dbo.task_age_days
-- from virtualColumnFunction — T-SQL scalar UDFs need the schema prefix).
EXEC(N'
CREATE OR ALTER FUNCTION dbo.task_age_days(@ts datetimeoffset)
RETURNS int
AS BEGIN
  RETURN IIF(DATEDIFF(day, @ts, SYSDATETIMEOFFSET()) < 0, 0, DATEDIFF(day, @ts, SYSDATETIMEOFFSET()));
END
');

-- Stored procedure exposed via the `storedProcedures` permission key. A real
-- PROCEDURE: Graphoria's MSSQL engine introspects sys.procedures / sys.parameters
-- and invokes with EXEC.
EXEC(N'
CREATE OR ALTER PROCEDURE dbo.project_stats @p_project_id int
AS BEGIN
  SET NOCOUNT ON;
  SELECT
    COUNT(CASE WHEN status = ''todo''        THEN 1 END) AS open_count,
    COUNT(CASE WHEN status = ''in_progress'' THEN 1 END) AS in_progress_count,
    COUNT(CASE WHEN status = ''done''        THEN 1 END) AS done_count
  FROM dbo.tasks WHERE project_id = @p_project_id;
END
');

-- ---- Seed data -------------------------------------------------------------

-- onConnect re-runs this file on every boot, so the explicit-id inserts must be
-- idempotent — the WHERE NOT EXISTS per row mirrors ON CONFLICT DO NOTHING.
SET IDENTITY_INSERT dbo.organizations ON;
INSERT INTO dbo.organizations (id, name, slug, [plan])
SELECT v.id, v.name, v.slug, v.[plan]
FROM (VALUES
  (1, N'Acme',   N'acme',   N'pro'),
  (2, N'Globex', N'globex', N'free')
) v (id, name, slug, [plan])
WHERE NOT EXISTS (SELECT 1 FROM dbo.organizations o WHERE o.id = v.id);
SET IDENTITY_INSERT dbo.organizations OFF;

SET IDENTITY_INSERT dbo.projects ON;
INSERT INTO dbo.projects (id, org_id, owner, name, description, visibility, status)
SELECT v.id, v.org_id, v.owner, v.name, v.description, v.visibility, v.status
FROM (VALUES
  (1, 1, N'alice', N'Website Redesign', N'Marketing site refresh',  N'org',     N'active'),
  (2, 1, N'molly', N'Public Roadmap',   N'Customer-facing roadmap', N'public',  N'active'),
  (3, 2, N'gina',  N'Internal Tools',   N'Ops tooling',             N'private', N'active')
) v (id, org_id, owner, name, description, visibility, status)
WHERE NOT EXISTS (SELECT 1 FROM dbo.projects p WHERE p.id = v.id);
SET IDENTITY_INSERT dbo.projects OFF;

-- Relative to 2026-06-28: tasks 1 and 4 are overdue (due in the past, not done).
SET IDENTITY_INSERT dbo.tasks ON;
INSERT INTO dbo.tasks (id, org_id, project_id, assignee, created_by, title, description, status, priority, due_date)
SELECT v.id, v.org_id, v.project_id, v.assignee, v.created_by, v.title, v.description, v.status, v.priority, v.due_date
FROM (VALUES
  (1, 1, 1, N'evan',  N'alice', N'Design homepage',  N'Hero + nav',     N'in_progress', 4, '2026-06-01'),
  (2, 1, 1, N'molly', N'alice', N'Set up CI',        N'GitHub Actions', N'todo',        3, '2026-12-01'),
  (3, 1, 2, N'evan',  N'molly', N'Write changelog',  N'v1 notes',       N'done',        2, '2026-06-10'),
  (4, 2, 3, N'max',   N'gina',  N'Migrate database', N'Move to PG 18',  N'todo',        5, '2026-06-15')
) v (id, org_id, project_id, assignee, created_by, title, description, status, priority, due_date)
WHERE NOT EXISTS (SELECT 1 FROM dbo.tasks t WHERE t.id = v.id);
SET IDENTITY_INSERT dbo.tasks OFF;

SET IDENTITY_INSERT dbo.comments ON;
INSERT INTO dbo.comments (id, org_id, task_id, author, body)
SELECT v.id, v.org_id, v.task_id, v.author, v.body
FROM (VALUES
  (1, 1, 1, N'molly', N'Looks good — ship it'),
  (2, 1, 1, N'evan',  N'Working on the nav now'),
  (3, 2, 4, N'gina',  N'Bumping priority to 5')
) v (id, org_id, task_id, author, body)
WHERE NOT EXISTS (SELECT 1 FROM dbo.comments c WHERE c.id = v.id);
SET IDENTITY_INSERT dbo.comments OFF;

SET IDENTITY_INSERT dbo.tags ON;
INSERT INTO dbo.tags (id, org_id, name, color)
SELECT v.id, v.org_id, v.name, v.color
FROM (VALUES
  (1, 1, N'frontend', N'#3b82f6'),
  (2, 1, N'backend',  N'#ef4444'),
  (3, 2, N'infra',    N'#10b981')
) v (id, org_id, name, color)
WHERE NOT EXISTS (SELECT 1 FROM dbo.tags t WHERE t.id = v.id);
SET IDENTITY_INSERT dbo.tags OFF;

INSERT INTO dbo.task_tags (task_id, tag_id)
SELECT v.task_id, v.tag_id
FROM (VALUES (1, 1), (2, 2), (4, 3)) v (task_id, tag_id)
WHERE NOT EXISTS (
  SELECT 1 FROM dbo.task_tags tt WHERE tt.task_id = v.task_id AND tt.tag_id = v.tag_id
);

SET IDENTITY_INSERT dbo.audit_log ON;
INSERT INTO dbo.audit_log (id, org_id, actor, action, entity)
SELECT v.id, v.org_id, v.actor, v.action, v.entity
FROM (VALUES
  (1, 1, N'alice', N'project.created', N'project:1')
) v (id, org_id, actor, action, entity)
WHERE NOT EXISTS (SELECT 1 FROM dbo.audit_log a WHERE a.id = v.id);
SET IDENTITY_INSERT dbo.audit_log OFF;
