import { mkdir, writeFile } from "node:fs/promises";
import { arch, cpus, platform, release, totalmem } from "node:os";
import { join } from "node:path";

import type { Summary } from "./stats";
import type { DatabaseType } from "../src/types/configuration";

import { MYSQL_CONNECTION_OPTIONS } from "../src/__test/integration/config";
import { startServer } from "../src/__test/integration/harness";
import { BENCH_SCHEMAS, ENGINES, ROW_COUNTS, benchConnection } from "./config";
import { CACHED_OPERATION, CACHED_OPERATION_PATH, listQuery, scenarios } from "./scenarios";
import { seedBench } from "./seed";
import { summarize } from "./stats";

/**
 * `bun run bench` — measures the six workloads in `scenarios.ts` against a real
 * server on a real engine and writes a reproducible report to `results/`.
 *
 *   bun run bench                       PostgreSQL, seeded, 200 iterations
 *   bun run bench -- --engine=mysql     another engine
 *   bun run bench -- --no-seed          reuse the dataset already in place
 *   bun run bench -- --iterations=500 --warmup=50
 *
 * Requests are issued one at a time over HTTP, so the latency figures are
 * single-client service time and the throughput figure is what one client can
 * drive — not a saturation number. Measuring saturation needs a load generator
 * that is not co-located with the server; see README.md.
 */

const RESULTS_DIR = join(import.meta.dir, "results");

const flag = (name: string) =>
  Bun.argv.find((argument) => argument.startsWith(`--${name}=`))?.split("=")[1];

const options = {
  engine: (flag("engine") ?? "pg") as DatabaseType,
  iterations: Number(flag("iterations") ?? 200),
  warmup: Number(flag("warmup") ?? 20),
  seed: !Bun.argv.includes("--no-seed"),
};

if (!ENGINES.includes(options.engine)) {
  throw new Error(`--engine must be one of ${ENGINES.join(", ")}, got ${options.engine}`);
}

const VERSION_QUERY: Record<DatabaseType, string> = {
  pg: "SELECT version() AS version",
  mysql: "SELECT VERSION() AS version",
  mssql: "SELECT @@VERSION AS version",
};

type ScenarioResult = Summary & { name: string; description: string };

type Report = {
  engine: DatabaseType;
  engineVersion: string;
  iterations: number;
  warmup: number;
  rows: typeof ROW_COUNTS;
  hardware: {
    cpu: string;
    cores: number;
    memoryGiB: number;
    platform: string;
    release: string;
    arch: string;
    bun: string;
  };
  recordedAt: string;
  scenarios: ScenarioResult[];
};

const benchConfig = (engine: DatabaseType) => ({
  name: "graphoria-bench",
  version: "1.0.0",
  databases: [
    {
      name: "default",
      enabled: true,
      type: engine,
      connection: benchConnection(engine),
      ...(engine === "mysql" ? { connectionOptions: MYSQL_CONNECTION_OPTIONS } : {}),
    },
  ],
  auth: {
    enabled: false,
    database: "",
    // `operations` defaults to [] per role, so the cached route is filtered out
    // of the anonymous schema unless the permission is spelled out.
    permissions: {
      anonymous: { tables: "ALL", storedProcedures: "ALL", operations: "ALL" },
    },
  },
  operations: {
    [CACHED_OPERATION]: {
      query: listQuery(engine),
      rest: { path: CACHED_OPERATION_PATH, method: "GET" },
      cache: { ttl: 60_000 },
    },
  },
});

const measure = async (run: () => Promise<void>, iterations: number, warmup: number) => {
  for (let index = 0; index < warmup; index += 1) await run();

  const samples: number[] = [];
  for (let index = 0; index < iterations; index += 1) {
    const started = Bun.nanoseconds();
    await run();
    samples.push((Bun.nanoseconds() - started) / 1e6);
  }

  return samples;
};

const ms = (value: number) => value.toFixed(2);

const renderMarkdown = (report: Report) => {
  const rows = report.scenarios
    .map(
      (scenario) =>
        `| \`${scenario.name}\` | ${ms(scenario.p50)} | ${ms(scenario.p95)} | ${ms(scenario.p99)} | ${ms(scenario.mean)} | ${scenario.throughputPerSecond.toFixed(1)} |`,
    )
    .join("\n");

  const descriptions = report.scenarios
    .map((scenario) => `- \`${scenario.name}\` — ${scenario.description}`)
    .join("\n");

  return `# Benchmark — ${report.engine}

Generated by \`bun run bench -- --engine=${report.engine}\`. Do not edit by hand.

- Recorded: ${report.recordedAt}
- Engine: ${report.engineVersion}
- Dataset: ${report.rows.users} users, ${report.rows.projects} projects, ${report.rows.tasks} tasks (schema \`${BENCH_SCHEMAS[report.engine]}\`)
- Iterations: ${report.iterations} measured, ${report.warmup} discarded as warmup
- Hardware: ${report.hardware.cpu}, ${report.hardware.cores} cores, ${report.hardware.memoryGiB} GiB, ${report.hardware.platform} ${report.hardware.release} (${report.hardware.arch}), Bun ${report.hardware.bun}

| scenario | p50 ms | p95 ms | p99 ms | mean ms | ops/s |
| --- | ---: | ---: | ---: | ---: | ---: |
${rows}

## Scenarios

${descriptions}

## Reading these numbers

Requests are issued one at a time from a client on the same host as the
database container, so the figures are single-client service time under no
contention. They are useful as a baseline to detect regressions against, and as
a relative comparison between scenarios. They are not a saturation throughput
number and they are not a cross-product comparison.

\`nested\` resolves in a single statement whatever the parent count or nesting
depth — the child rows are correlated subqueries inside the parent's statement.
The per-parent work is still there, inside the engine's plan. See
\`src/__test/integration/perf/n-plus-one.test.ts\`.
`;
};

const main = async () => {
  const { engine, iterations, warmup } = options;

  if (options.seed) {
    console.log(`seeding ${engine}…`);
    await seedBench(engine);
  }

  console.log(`booting a server against ${engine}…`);
  const { context, stop } = await startServer({
    engine,
    skipSeed: true,
    config: benchConfig(engine) as never,
  });

  try {
    const [version] = await context.sql<{ version: string }>(VERSION_QUERY[engine]);

    const results: ScenarioResult[] = [];
    for (const scenario of scenarios(engine)) {
      process.stdout.write(`  ${scenario.name}… `);
      const samples = await measure(() => scenario.run(context), iterations, warmup);
      const summary = summarize(samples);
      results.push({ ...summary, name: scenario.name, description: scenario.description });
      console.log(`p50 ${ms(summary.p50)}ms  p95 ${ms(summary.p95)}ms`);
    }

    const report: Report = {
      engine,
      engineVersion: (version?.version ?? "unknown").split("\n")[0]!.trim(),
      iterations,
      warmup,
      rows: ROW_COUNTS,
      hardware: {
        cpu: cpus()[0]?.model.trim() ?? "unknown",
        cores: cpus().length,
        memoryGiB: Math.round(totalmem() / 1024 ** 3),
        platform: platform(),
        release: release(),
        arch: arch(),
        bun: Bun.version,
      },
      recordedAt: new Date().toISOString(),
      scenarios: results,
    };

    await mkdir(RESULTS_DIR, { recursive: true });
    await writeFile(join(RESULTS_DIR, `${engine}.json`), `${JSON.stringify(report, null, 2)}\n`);
    await writeFile(join(RESULTS_DIR, `${engine}.md`), renderMarkdown(report));

    console.log(`\nwrote results/${engine}.json and results/${engine}.md`);
  } finally {
    await stop();
  }
};

await main();
